export const actionTypes = {
    CREATE_DAO: "createDao"
}

export const messages = {
    CREATE_DAO_SUCCESS: "Create new DAO successful",
    FAIL_CREATE_DAO: "Fail to create new DAO",
    CREATE_DAO_TITLE: "Create new DAO",
    CREATE_PROGRAM_SUCCESS: "Create new program successful",
    FAIL_CREATE_PROGRAM: "Fail to create new program",
    CREATE_PROGRAM_TITLE: "Create new program",
    CREATE_PROPOSAL_SUCCESS: "Create new proposal successful",
    FAIL_CREATE_PROPOSAL: "Fail to create new proposal",
    CREATE_PROPOSAL_TITLE: "Create new proposal",
    FUND_SUCCESS: "Fund DAO successful",
    FAIL_TO_FUND: "Fail to fund this DAO",
    FUND_TITLE: "Fund this DAO",
    VOTING_TITLE: "Voting",
    VOTING_SUCCESS: "Vote the proposal successful",
    FAIL_TO_VOTE: "Fail to vote",
    EXECUTE_PROPOSAL_TITLE: "Proposal execution",
    EXECUTE_PROPOSAL_SUCCESS: "Execute the proposal successful",
    FAIL_TO_EXECUTE: "Fail to execute the proposal",
    ADD_MEMBER_TITLE: "New Member",
    ADD_MEMBER_SUCCESS: "Add new member successful",
    FAIL_TO_ADD_MEMBER: "Fail to add new member",
    REMOVE_MEMBER_TITLE: "Remove Member",
    REMOVE_MEMBER_SUCCESS: "Remove old member successful",
    FAIL_TO_REMOVE_MEMBER: "Fail to remove old member",
    REMOVE_CONTRIBUTOR_TITLE: "Remove Contributor",
    REMOVE_CONTRIBUTOR_SUCCESS: "Remove old contributor successful",
    FAIL_TO_REMOVE_CONTRIBUTOR: "Fail to remove old contributor",
    ADD_CONTRIBUTOR_TITLE: "Add Contributor",
    ADD_CONTRIBUTOR_SUCCESS: "Add new contributor successful",
    FAIL_TO_ADD_CONTRIBUTOR: "Fail to add new contributor",
    ADD_STEP_MEMBER_TITLE: "Add step member",
    ADD_STEP_MEMBER_SUCCESS: "Add new step member successful",
    FAIL_TO_ADD_STEP_MEMBER: "Fail to add new step member",
    REMOVE_STEP_MEMBER_TITLE: "Remove step member",
    REMOVE_STEP_MEMBER_SUCCESS: "Remove step member successful",
    FAIL_TO_REMOVE_STEP_MEMBER: "Fail to remove step member",
}